// widget/svelte/Widget.svelte
<script>
  import { onDestroy, onMount } from "svelte"
  import { mountWidget } from "../core/mountWidget.js"

  export let agentId
  export let baseUrl
  export let scriptSrc
  export let containerId
  export let components

  let widget = null
  let mounted = false

  const normalizeComponents = (entries) => {
    if (!Array.isArray(entries)) return undefined
    return entries.map((entry) => {
      if (!entry || !entry.component) return entry
      return {
        key: entry.key,
        version: entry.version,
        render: ({ mount, props }) => {
          const instance = new entry.component({ target: mount, props })
          return () => instance.$destroy?.()
        }
      }
    })
  }

  const unmount = () => {
    if (widget) {
      widget.unmount()
      widget = null
    }
  }

  onMount(() => {
    mounted = true
  })

  $: if (mounted) {
    unmount()
    if (agentId && scriptSrc) {
      widget = mountWidget({ agentId, baseUrl, scriptSrc, containerId, components: normalizeComponents(components) })
    }
  }

  onDestroy(() => {
    unmount()
  })
</script>

// widget/vue/Widget.vue
<script setup lang="ts">
import { createApp, h, onBeforeUnmount, onMounted, watch } from "vue"
import { mountWidget, type MountedWidget } from "../core/mountWidget"

const props = defineProps<{
  agentId: string
  baseUrl?: string
  scriptSrc: string
  containerId?: string
  components?: unknown[]
}>()

let widget: MountedWidget | null = null

const normalizeComponents = (components?: unknown[]) => {
  if (!Array.isArray(components)) return undefined
  return components.map((entry) => {
    if (!entry || typeof entry !== "object" || !("component" in entry)) return entry
    const componentEntry = entry as { key?: string; version?: string; component?: unknown }
    if (!componentEntry.component) return entry
    return {
      key: componentEntry.key,
      version: componentEntry.version,
      render: ({ mount, props }: { mount: Element; props: Record<string, unknown> }) => {
        const app = createApp({ render: () => h(componentEntry.component as object, props) })
        app.mount(mount)
        return () => app.unmount()
      }
    }
  })
}

const mount = () => {
  widget?.unmount()
  widget = mountWidget({
    agentId: props.agentId,
    baseUrl: props.baseUrl,
    scriptSrc: props.scriptSrc,
    containerId: props.containerId,
    components: normalizeComponents(props.components)
  })
}

onMounted(mount)

watch(
  () => [props.agentId, props.baseUrl, props.scriptSrc, props.containerId, props.components],
  () => mount()
)

onBeforeUnmount(() => {
  widget?.unmount()
  widget = null
})
</script>
